# Python4ev1: database

## Table of contents
1. [Objected oriented Python](#object) : [\[Unicode\]](#unicode)
2. [Basic structured query language](#sql_basic) : [\[Sqlite3\]](#sqlite3) - [\[Twspider\]](#twspider)
3. [Data model and relational SQL](#data_model) : [\[JOIN clause\]](#join)
4. [Many-to-many relationships in SQL](#m2m_sql) : [\[Twfriends\]](#twfriends)
5. [Databases and visualization](#visual) : [\[JS geocode\]](#jsgeo)
 [](#)

A review of the Unicode format. <a name= 'unicode'></a>

In [2]:
# Review of the Unicode (UTF-8) format of Python 3
# as oppose to ASCII
# Use .encode() or .decode() to handle byte data

x1 = 'o'
x2 = 'O'
x3 = '0'

print(x1, ord(x1))
print(x2, ord(x2))
print(x3, ord(x3))

help(ord)

o 111
O 79
0 48
Help on built-in function ord in module builtins:

ord(c, /)
    Return the Unicode code point for a one-character string.

## 1. Object oriented programming and terminologies <a name= 'object'></a>

### Class and object
- `Class`: a template / blue-print to make objects
- `Method/message`: a defiend capability of a class
- `Attribute/field`: a bit of data in a class
- `Instance/object`: a particular instance of a class
- `__init__/__del__` : 'Constructor/Destructor' - methods used to make/delete an obj (destructors are rarely used)
- `Iheritance` : the ability to extend a class to make new class

See the [web access](./python4ev1_accessWeb.ipynb#class) session notes for more examples.

In [ ]:
# None

## 2. Basic structured query language <a name= 'sql_basic'></a>

### Relational databases
> __Relational databases__ are flat (row and column) table designed to optimize the efficiency of retrieving data, especially when multiple related tables are involved in a query.

- Database : a library of tables
- Relation (table) : contains tuples and attributes
- Tuple (row) : a set of fields that generally represents an object
- Attributes (column) : one of the possible elements of data corresponding to an object represented by the row

In a spreadsheet, the top row is practically a "schema" of storing the data.

### Structured query language (SQL) <a name= 'sql'></a>
> SQL is used to issue commands to the database to: create table and retrieve/ updata/ delete data (CRUD).

A database model or database schema is the structure/feature of the database described in formal language supported by the database management system. The example sql code (sqlite style) below are NOT excecutable.

In [ ]:
# SQLite code (Not excutable)
CREATE TABLE Users (
    name VARCHAR(128),
    email VARCHAR(128)
); # case matters and len is specified

# Insert item
INSERT INTO Users (name, email) VALUES ('Grump', 'grump@ucls.edu')

# Delete item (WHERE for select)
DELETE FROM Users WHERE name='Tim'

# Update item
UPDATE Users SET name='Chris' WHERE email='chris@purdue.edu'

# Retrieve data (filtering by WHERE clause)
SELECT * FROM Users WHERE name='Fred' # slect all fields

# Retrieve ordered data
SELECT * FROM Users ORDER BY name

### Using the Sqllite3 moduleb <a name= 'sqlite3'></a>

Making connection -> assign cursor -> data access and manipulation -> close connection through the cursor. The `row` is used to cache the item but not used to count. All the countings are accomplished by direct `UPDATE`, a good practice if multiple users are accessing the same database at the same time.

The `conn.commit()` will commit the changes by writing them to the hard drive (as opposed to in the RAM), thus is a slow step. For online system, it's best to commit every time a change is made; for local databse, you may commit every 10 times e.g. .

In [6]:
import sqlite3

# open the sql connection
conn = sqlite3.connect('emaildb.sqlite') # Create the db if not existed
cur = conn.cursor() # assign ti to a cursor

# drop the previous result
cur.execute('DROP TABLE IF EXISTS Counts')
# create new table
cur.execute('''
CREATE TABLE Counts (email TEXT, count INTEGER)''')

fname = input('Enter file name: ')
if (len(fname) < 1): fname = 'mbox-short.txt' # the imput file
fh = open(fname)

for line in fh:
    # read all email addresses from the txt
    if not line.startswith('From: '): continue
    pieces = line.split()
    email = pieces[1]
    
    # select if the address exists
    cur.execute('SELECT count FROM Counts WHERE email = ? ', (email,)) # '?' placeholder indicating var inputs
    # the var input need to be a tuple (even only one var)
    
    # Now the cur id a list of count column, fetch the first one
    row = cur.fetchone() # row is a tuple
    if row is None: # new address
        cur.execute('''INSERT INTO Counts (email, count)
                VALUES (?, 1)''', (email,))
    else: # UPDATE is more atomic action especially when multiple users are accessing the db
        cur.execute('UPDATE Counts SET count = count + 1 WHERE email = ?',
                    (email,))
    # commit the change thru the connection
    conn.commit()

# https://www.sqlite.org/lang_select.html
sqlstr = 'SELECT email, count FROM Counts ORDER BY count DESC LIMIT 10'
# LIMIT get the first 10 items

for row1 in cur.execute(sqlstr):
    print(row1[1], str(row1[0]))

# close the connection
cur.close()

Enter file name:
5 cwen@iupui.edu
4 zqian@umich.edu
4 david.horwitz@uct.ac.za
3 louis@media.berkeley.edu
3 gsilver@umich.edu
2 stephen.marquard@uct.ac.za
2 rjlowe@iupui.edu
1 wagnermr@iupui.edu
1 antranig@caret.cam.ac.uk
1 gopal.ramasammycook@gmail.com

In [8]:
row # it's a tuple values EXCLUDING the filter

(4,)

### Twspider <a name= 'twspider'></a>
Retrieving the friend number of your input username's friends', still NOT USABLE since it needs oath key and tokens.

In [10]:
from urllib.request import urlopen
import urllib.error
import twurl
import json
import sqlite3
import ssl

TWITTER_URL = 'https://api.twitter.com/1.1/friends/list.json'

conn = sqlite3.connect('spider.sqlite')
cur = conn.cursor()

cur.execute('''
            CREATE TABLE IF NOT EXISTS Twitter
            (name TEXT, retrieved INTEGER, friends INTEGER)''')

# Ignore SSL certificate errors
ctx = ssl.create_default_context()
ctx.check_hostname = False
ctx.verify_mode = ssl.CERT_NONE

while True:
    acct = input('Enter a Twitter account, or quit: ')
    if (acct == 'quit'): break
    if (len(acct) < 1):
        cur.execute('SELECT name FROM Twitter WHERE retrieved = 0 LIMIT 1')
        try:
            acct = cur.fetchone()[0]
        except:
            print('No unretrieved Twitter accounts found')
            continue

    url = twurl.augment(TWITTER_URL, {'screen_name': acct, 'count': '5'})
    print('Retrieving', url)
    connection = urlopen(url, context=ctx)
    data = connection.read().decode()
    headers = dict(connection.getheaders())

    print('Remaining', headers['x-rate-limit-remaining'])
    js = json.loads(data)
    # Debugging
    # print json.dumps(js, indent=4)

    cur.execute('UPDATE Twitter SET retrieved=1 WHERE name = ?', (acct, ))

    countnew = 0
    countold = 0
    for u in js['users']:
        friend = u['screen_name']
        print(friend)
        cur.execute('SELECT friends FROM Twitter WHERE name = ? LIMIT 1',
                    (friend, ))
        try:
            count = cur.fetchone()[0]
            cur.execute('UPDATE Twitter SET friends = ? WHERE name = ?',
                        (count+1, friend))
            countold = countold + 1
        except:
            cur.execute('''INSERT INTO Twitter (name, retrieved, friends)
                        VALUES (?, 0, 1)''', (friend, ))
            countnew = countnew + 1
    print('New accounts=', countnew, ' revisited=', countold)
    conn.commit()

cur.close()

Enter a Twitter account, or quit:
No unretrieved Twitter accounts found
Enter a Twitter account, or quit: quit

## 3. Data model and relational SQL <a name= 'data_model'></a>
> __Concepts__: <br> 1. Draw a pricture of the data class in the application and figure out how to represent the objects and their relationshipd. <br> 2. Don't put in the same string data twice -> use relationships. <br> 3. When there's one thing in the real world, there'd be one thing in the databas.

### Rules for data model
- Think of if the field repr a real world object, or the attr of an object.
- Start with the field that is most essential to /closely-associated with your application.
- Define the relations between the objects.
- Mapping the objects and relations into a database model/schema (__logical model -> physical model__).
- Each table shall have a __primary key__ used to track each entry, which is the endpoint of a relation arrow.
- A __foreign key__ is used to point to (starting point) another table.
- A __logical key__ is the field used to look up things in the user interface or api (might be used in WHERE/ORDER BY clause).
- A database should be constructed __from the end to the root__ (start with the least no. of relations).

### Reconstructing data using JOIN <a name='join'></a>
> By removing replicated data and replace it with references, a 'web' of information was constructed which can be constructed to enable fast access by relational database. This is achieved by using the __foreign keys__.

For example: `SELECT TabA.attrA TabB.attrB FROM TabA JOIN TabB ON TabA.TabB_id = TabB.id` can be sed to join table A and B and retrieving attr A and B by using the table B id as a reference. (Some SQL services use WHERE clause instead of ON. )

For another Example: joining four tables wheere D<-A->B->C:
`SELECT A.a, B.b, C.c, D.d FROM A JOIN B JOIN C JOIN D ON A.B_id=B.id AND A.D_id-D.id AND B.C_id=C.id`

In [1]:
# Converting the XML iTunes lib to JSON style Sqlite DB
import xml.etree.ElementTree as ET
import sqlite3

# Create the db
conn = sqlite3.connect('./tracks/trackdb.sqlite')
cur = conn.cursor()

# Make some fresh tables using executescript()
cur.executescript('''
DROP TABLE IF EXISTS Artist;
DROP TABLE IF EXISTS Album;
DROP TABLE IF EXISTS Track;

CREATE TABLE Artist (
    id  INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
    name    TEXT UNIQUE
);

CREATE TABLE Album (
    id  INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
    artist_id  INTEGER,
    title   TEXT UNIQUE
);

CREATE TABLE Track (
    id  INTEGER NOT NULL PRIMARY KEY 
        AUTOINCREMENT UNIQUE,
    title TEXT  UNIQUE,
    album_id  INTEGER,
    len INTEGER, rating INTEGER, count INTEGER
);
''') # some str are set to be unique


fname = input('Enter file name: ')
if ( len(fname) < 1 ) : fname = './tracks/Library.xml'

# <key>Track ID</key><integer>369</integer>
# <key>Name</key><string>Another One Bites The Dust</string>
# <key>Artist</key><string>Queen</string>
def lookup(d, key):
    found = False
    for child in d:
        if found : return child.text
        if child.tag == 'key' and child.text == key :
            found = True
    return None

# Parsing it like a tree (xml)
stuff = ET.parse(fname)
all = stuff.findall('dict/dict/dict')
print('Dict count:', len(all))
for entry in all:
    if ( lookup(entry, 'Track ID') is None ) : continue

    name = lookup(entry, 'Name')
    artist = lookup(entry, 'Artist')
    album = lookup(entry, 'Album')
    count = lookup(entry, 'Play Count')
    rating = lookup(entry, 'Rating')
    length = lookup(entry, 'Total Time')

    if name is None or artist is None or album is None : 
        continue

    print(name, artist, album, count, rating, length)
    
    # IGNORE unique to sqlite will ignore duplicates for fields defined as unique
    # otherwise Error meddages will pop up
    cur.execute('''INSERT OR IGNORE INTO Artist (name) 
        VALUES ( ? )''', ( artist, ) )
    cur.execute('SELECT id FROM Artist WHERE name = ? ', (artist, ))
    artist_id = cur.fetchone()[0]
    # Once the artist is in the db retieve its ID

    cur.execute('''INSERT OR IGNORE INTO Album (title, artist_id) 
        VALUES ( ?, ? )''', ( album, artist_id ) )
    cur.execute('SELECT id FROM Album WHERE title = ? ', (album, ))
    album_id = cur.fetchone()[0]
    
    # REPLACE unique to sqlite: update pre-existing unique entry without poping errors
    cur.execute('''INSERT OR REPLACE INTO Track
        (title, album_id, len, rating, count) 
        VALUES ( ?, ?, ?, ?, ? )''', 
        ( name, album_id, length, rating, count ) )

    conn.commit()

cur.close()

Enter file name:
Dict count: 404
Another One Bites The Dust Queen Greatest Hits 55 100 217103
Asche Zu Asche Rammstein Herzeleid 79 100 231810
Beauty School Dropout Various Grease 48 100 239960
Black Dog Led Zeppelin IV 109 100 296620
Bring The Boys Back Home Pink Floyd The Wall [Disc 2] 33 100 87118
Circles Bryan Lee Blues Is 54 60 355369
Comfortably Numb Pink Floyd The Wall [Disc 2] 36 100 384130
Crazy Little Thing Called Love Queen Greatest Hits 38 100 163631
Electric Funeral Black Sabbath Paranoid 44 100 293015
Fat Bottomed Girls Queen Greatest Hits 38 100 257515
For Those About To Rock (We Salute You) AC/DC Who Made Who 84 100 353750
Four Sticks Led Zeppelin IV 84 100 284421
Furious Angels Rob Dougan The Matrix Reloaded 54 100 330004
Gelle Bryan Lee Blues Is 45 60 199836
Going To California Led Zeppelin IV 100 100 215666
Grease Various Grease 42 100 205792
Hand of Doom Black Sabbath Paranoid 36 100 429609
Hells Bells AC/DC Who Made Who 82 100 312946
Hey You Pink Floyd The Wall [Disc 2] 23 100 282305
I Worry Bryan Lee Blues Is 33 100 341315
Iron Man Black Sabbath Paranoid 39 100 358530
Is There Anybody Out There? Pink Floyd The Wall [Disc 2] 26 100 160679
It was a Very Good Year Frank Sinatra Greatest Hits 39 100 268852
Its Your Move Bryan Lee Blues Is 40 100 245002
Jack the Stripper/Fairies Wear Boots Black Sabbath Paranoid 35 100 373995
Killer Queen Queen Greatest Hits 34 100 181368
Laichzeit Rammstein Herzeleid 41 100 262844
Let me Down Easy Bryan Lee Blues Is 43 100 331441
Misty Mountain Hop Led Zeppelin IV 88 100 278831
No Low Down Bryan Lee Blues Is 39 100 245760
Now You Are Gone America Greatest Hits 52 100 187559
Outside The Wall Pink Floyd The Wall [Disc 2] 16 100 104437
Paranoid Black Sabbath Paranoid 36 100 172930
Planet Caravan Black Sabbath Paranoid 38 100 274938
Pretty Jeanie Bryan Lee Blues Is 34 100 225175
Rammstein Rammstein Herzeleid 45 100 265090
Rat Salad Black Sabbath Paranoid 46 100 150230
Rock & Roll Led Zeppelin IV 109 100 220891
Rode Across the Desert America Greatest Hits 60 100 249887
Sandy Various Grease 36 100 155742
Shake Your Foundations AC/DC Who Made Who 85 100 233769
Sister Golden Hair America Greatest Hits 60 100 202057
Somebody To Love Queen Greatest Hits 17 100 297586
Stairway To Heaven Led Zeppelin IV 93 100 481567
Strangers in the Night Frank Sinatra Greatest Hits 42 100 158484
Summer Nights Various Grease 35 100 216973
Summer Wind Frank Sinatra Greatest Hits 46 100 177554
Thats Life Frank Sinatra Greatest Hits 43 100 189988
The Battle Of Evermore Led Zeppelin IV 110 100 351529
The Blues "Is" Bryan Lee Blues Is 45 100 252238
There it Is Bryan Lee Blues Is 35 100 395441
Think Bryan Lee Blues Is 41 100 320339
This Town Frank Sinatra Greatest Hits 44 100 185051
Tin Man America Greatest Hits 50 100 210076
Track 01 Billy Price Danger Zone 47 100 261825
Track 02 Billy Price Danger Zone 42 100 165459
Track 03 Billy Price Danger Zone 41 100 206471
Messin with the Kid The Canettes Blues Band Self Titled 23 100 226377
Track 04 Billy Price Danger Zone 37 100 257175
Stormy Monday The Canettes Blues Band Self Titled 29 100 464143
Track 05 Billy Price Danger Zone 42 100 230295
Waiting on Ice Bryan Lee Blues Is 37 100 289384
War Pigs/Luke's Wall Black Sabbath Paranoid 38 100 478197
We Are The Champions Queen Greatest Hits 24 100 181864
We Will Rock You Queen Greatest Hits 33 100 123559
When Somebody Loves You Frank Sinatra Greatest Hits 43 100 117263
When The Levee Breaks Led Zeppelin IV 83 100 427624
You are the One that I Want Various Grease 31 100 169900
You Done Me Wrong Bryan Lee Blues Is 35 100 200097
You Shook Me All Night Long AC/DC Who Made Who 92 100 210938
You're My Best Friend Queen Greatest Hits 31 100 172643
Zion Fluke The Matrix Reloaded 47 100 273528
Who Made Who AC/DC Who Made Who 110 100 207203
D.T. AC/DC Who Made Who 90 None 173714
Sink the Pink AC/DC Who Made Who 83 None 253466
Ride On AC/DC Who Made Who 75 None 351268
Chase the Ace AC/DC Who Made Who 93 None 181420
Wollt Ihr Das Bett In Flammen Sehen Rammstein Herzeleid 50 None 317387
Der Meister Rammstein Herzeleid 46 None 250801
Weisses Fleisch Rammstein Herzeleid 52 None 215902
Seemann Rammstein Herzeleid 34 None 288235
Du Riechst So Gut Rammstein Herzeleid 50 None 289332
Das Alte Leid Rammstein Herzeleid 46 None 344581
Heirate Mich Rammstein Herzeleid 39 None 284734
Herzeleid Rammstein Herzeleid 42 None 223425
Baba O'Riley The Who Who's Next 45 None 298448
Bargain The Who Who's Next 37 None 331676
Love Ain't for Keeping The Who Who's Next 24 None 130560
My Wife The Who Who's Next 17 None 213786
The Song Is Over The Who Who's Next 14 None 375797
Getting In Tune The Who Who's Next 27 None 288809
Going Mobile The Who Who's Next 28 100 221910
Behind Blue Eyes The Who Who's Next 43 None 221570
Won't Get Fooled Again The Who Who's Next 21 None 511111
Folsom Prison Blues Johnny Cash The Legend Of Johnny Cash 47 100 170004
I Walk The Line Johnny Cash The Legend Of Johnny Cash 33 100 165720
Get Rhythm Johnny Cash The Legend Of Johnny Cash 35 100 134530
Big River Johnny Cash The Legend Of Johnny Cash 51 None 152711
Guess Things Happen That Way Johnny Cash The Legend Of Johnny Cash 35 None 111386
Ring Of Fire Johnny Cash The Legend Of Johnny Cash 30 100 157100
Jackson Johnny Cash The Legend Of Johnny Cash 35 100 166530
A Boy Named Sue (live) Johnny Cash The Legend Of Johnny Cash 37 None 226063
You Raise Me Up Selah Hiding Place 9 None 302262
Hold On, I'm Coming The Canettes Blues Band On Tap & In the Can 34 100 282566
Got my Mojo Working The Canettes Blues Band On Tap & In the Can 52 100 310517
Sweet Home Chicago The Canettes Blues Band On Tap & In the Can 27 100 375849
Heavy Love The Canettes Blues Band On Tap & In the Can 28 100 253544
Cold Cold Feeling The Canettes Blues Band On Tap & In the Can 43 100 261929
Lonely Avenue The Canettes Blues Band On Tap & In the Can 24 100 292022
Good Morning Little Schoolgirl The Canettes Blues Band On Tap & In the Can 20 100 278648
Dust My Broom The Canettes Blues Band On Tap & In the Can 24 100 299311
Gimme' Some Lovin The Canettes Blues Band On Tap & In the Can 35 100 227239
Everybody Needs Somebody to Love The Canettes Blues Band On Tap & In the Can 24 100 195186
Black Magic Woman The Canettes Blues Band On Tap & In the Can 31 100 442644
Steppin' Rooster The Canettes Blues Band On Tap & In the Can 21 100 704862
Our Love is Drifting The Canettes Blues Band On Tap & In the Can 15 100 292649
Doin' 100 The Canettes Blues Band On Tap & In the Can 20 100 343980
Mother Joy Matt Ender Natural Wonders Music Sampler 1999 463 None 287294
Soldier's Lament Steve McDonald Natural Wonders Music Sampler 1999 371 None 347193
Dulaman Altan Natural Wonders Music Sampler 1999 403 None 223007
The Arrow Chris Spheeris Natural Wonders Music Sampler 1999 416 None 319869
Spanish Eyes La Esperanza Natural Wonders Music Sampler 1999 375 None 259030
Banana Bay Luis Villegas Natural Wonders Music Sampler 1999 403 None 198060
Aguas De Marco Rosa Passos Natural Wonders Music Sampler 1999 407 None 179408
Tamborea Energipsy Natural Wonders Music Sampler 1999 355 None 235389
Gone Hollie Smith Natural Wonders Music Sampler 1999 362 None 196414
The Immigrant Joanie Madden Natural Wonders Music Sampler 1999 350 None 362631
Pahrump-Big Water Cusco Natural Wonders Music Sampler 1999 342 None 191634
Seeker's Quest Cheryl Gunn Natural Wonders Music Sampler 1999 337 None 236434
Floating To Forever Dean Everson Natural Wonders Music Sampler 1999 337 None 351686
Open Road Jeff Bailey Relaxing Jazz 10 None 318563
Ruby Kaiser Chiefs Yours Truly, Angry Mob 13 None 205008
The Angry Mob Kaiser Chiefs Yours Truly, Angry Mob 41 None 288313
Heat Dies Down Kaiser Chiefs Yours Truly, Angry Mob 12 None 237061
Highroyds Kaiser Chiefs Yours Truly, Angry Mob 10 None 199575
Love's Not A Competition (But I'm Winning) Kaiser Chiefs Yours Truly, Angry Mob 11 None 197799
Thank You Very Much Kaiser Chiefs Yours Truly, Angry Mob 11 None 157753
I Can Do It Without You Kaiser Chiefs Yours Truly, Angry Mob 11 None 204199
My Kind Of Guy Kaiser Chiefs Yours Truly, Angry Mob 10 None 246595
Everything Is Average Nowadays Kaiser Chiefs Yours Truly, Angry Mob 16 None 164754
Learnt My Lesson Well Kaiser Chiefs Yours Truly, Angry Mob 9 None 325955

Try Your Best Kaiser Chiefs Yours Truly, Angry Mob 8 None 222511
Retirement Kaiser Chiefs Yours Truly, Angry Mob 10 None 237426
The Angry Mob [Live From Berlin] Kaiser Chiefs Yours Truly, Angry Mob 40 None 279066
I Like To Fight Kaiser Chiefs Yours Truly, Angry Mob 8 None 218566
From The Neck Down Kaiser Chiefs Yours Truly, Angry Mob 15 None 147226
Bomb Squad (TECH) Brent Brent's Album 4 None 208065
BYURY ME Brent Peanut Butter & Jam  4 None 274076
Charlie and the Rising Moon Charlie And The Rising Moon Charlie and The Rising Moon None None 161645
clay techno  Brent Brent's Album 5 None 276062
Cloud Nine Times Over  Charlie And The Rising Moon Charlie and The Rising Moon 3 None 135131
Depression in Session Brent Peanut Butter and Jam  4 None 213211
Heavy Brent Brent's Album 2 None 188055
Hi metal man Brent Brent's Album 4 None 260153
Mistro Brent Brent's Album 5 None 178076
Pirate spirit Brent Brent's Album 3 None 180480
Run Away (New)  Brent Brent's Album 1 None 154383
Star Gaze (Inspired) Charlie And The Rising Moon Charlie and The Rising Moon None None 181498
The Dictator (New Brent Peanut Butter & Jam  5 None 143830
Town From Town Brent Brent's Album 4 None 86073
The Wisdom of Crowds: Why the Many Are Smarter than the Few Part 1 of 3 James Surowiecki The Wisdom of Crowds: Why the Many Are Smarter than the Few (Abridged Nonfiction) 15 None 8586749
The Wisdom of Crowds: Why the Many Are Smarter than the Few Part 2 of 3 James Surowiecki The Wisdom of Crowds: Why the Many Are Smarter than the Few (Abridged Nonfiction) 9 None 8443432
The Wisdom of Crowds: Why the Many Are Smarter than the Few Part 3 of 3 James Surowiecki The Wisdom of Crowds: Why the Many Are Smarter than the Few (Abridged Nonfiction) 3 None 4168829
The Wisdom of Crowds: Why the Many Are Smarter Than the Few (Unabridged) Part 1 of 5 James Surowiecki The Wisdom of Crowds: Why the Many Are Smarter Than the Few (Unabridged) 4 None 7920893
The Wisdom of Crowds: Why the Many Are Smarter Than the Few (Unabridged) Part 2 of 5 James Surowiecki The Wisdom of Crowds: Why the Many Are Smarter Than the Few (Unabridged) None None 7921106
The Wisdom of Crowds: Why the Many Are Smarter Than the Few (Unabridged) Part 3 of 5 James Surowiecki The Wisdom of Crowds: Why the Many Are Smarter Than the Few (Unabridged) None None 7965736
The Wisdom of Crowds: Why the Many Are Smarter Than the Few (Unabridged) Part 4 of 5 James Surowiecki The Wisdom of Crowds: Why the Many Are Smarter Than the Few (Unabridged) 1 None 9653330
The Wisdom of Crowds: Why the Many Are Smarter Than the Few (Unabridged) Part 5 of 5 James Surowiecki The Wisdom of Crowds: Why the Many Are Smarter Than the Few (Unabridged) None None 746536
Misty David Osborne Moonlight And Love Songs 302 None 249312
My Funny Valentine David Osborne Moonlight And Love Songs 301 None 235885
Since I Don't Have You David Osborne Moonlight And Love Songs 288 None 251846
Tenderly David Osborne Moonlight And Love Songs 284 None 227395
When I Fall In Love David Osborne Moonlight And Love Songs 281 None 187768
Unforgettable David Osborne Moonlight And Love Songs 280 None 272927
The Way You Look Tonight David Osborne Moonlight And Love Songs 277 None 247222
I've Grown Accustomed To Your Face David Osborne Moonlight And Love Songs 280 None 148035
Smoke Gets In Your Eyes David Osborne Moonlight And Love Songs 277 None 198504
Fly Me To The Moon David Osborne Moonlight And Love Songs 275 None 182543
Unchained Melody David Osborne Moonlight And Love Songs 265 None 259369
These Foolish Things Remind Me Of You David Osborne Moonlight And Love Songs 267 None 184711
La Vie En Rose David Osborne Moonlight And Love Songs 259 None 276767
As Time Goes By David Osborne Moonlight And Love Songs 290 None 257985
Pilot Fairly Legal Fairly Legal, Season 1 1 None 3847006
Jobs2a csev csev's Album None None 541074
hte postal service - the impor The Postal Service unreleased demo None None 193959
Winter Wonderland Bing Crosby Seasons Greatings 163 None 144744
Jingle Bells Frank Sinatra Seasons Greatings 271 None 121756
White Christmas Bing Crosby Seasons Greatings 158 None 95634
The Christmas Song Frank Sinatra Seasons Greatings 272 None 209632
Little Drummer Boy Bing Crosby Seasons Greatings 154 None 178311
Silent Night Frank Sinatra Seasons Greatings 257 None 149054
Let It Snow Bing Crosby Seasons Greatings 154 None 125126
Mistletoe And Holly Frank Sinatra Seasons Greatings 257 None 138501
O Holy Night Bing Crosby Seasons Greatings 150 None 214021
Have Yourself A Merry Little Christmas Frank Sinatra Seasons Greatings 252 None 208248
Do You Hear What I Hear Bing Crosby Seasons Greatings 155 None 164728
I'll Be Home For Christmas Frank Sinatra Seasons Greatings 249 None 190876
Voices Disturbed The Sickness None None 191764
The Game Disturbed The Sickness 1 None 227134
Stupify Disturbed The Sickness 1 None 274233
Down With The Sickness Disturbed The Sickness 1 None 278726
Violence Fetish Disturbed The Sickness None None 203833
Fear Disturbed The Sickness 4 None 227004
Numb Disturbed The Sickness None None 224940
Want Disturbed The Sickness None None 232803
Conflict Disturbed The Sickness 5 None 275330
Shout 2000 Disturbed The Sickness 1 None 257802
Droppin' Plates Disturbed The Sickness 4 None 229302
Meaning Of Life Disturbed The Sickness 3 None 242599
PY4INF-01-Intro.mp3 Recording by Dr. Chuck Python for Informatics's official Podcast. 1 None 3428075
Eben Upton: Raspberry Pi IEEE Computer Society Computing Conversations 2 None 661368
Andrew Tanenbaum: Writing the Book on Networks IEEE Computer Society Computing Conversations 4 None 535040
Massimo Banzi: Building Arduino IEEE Computer Society Computing Conversations 1 None 567745
PY4INF-04-Functions.mp3 Recording by Dr. Chuck Python for Informatics's official Podcast. None None 1683800
PY4INF-02-Expressions.mp3 Recording by Dr. Chuck Python for Informatics's official Podcast. None None 2578416
PY4INF-03-Conditional.mp3 Recording by Dr. Chuck Python for Informatics's official Podcast. None None 2296058
PY4INF-05-Iterations.mp3 Recording by Dr. Chuck Python for Informatics's official Podcast. 1 None 2804297
PY4INF-06-Strings.mp3 Recording by Dr. Chuck Python for Informatics's official Podcast. None None 1677844
PY4INF-07-Files.mp3 Recording by Dr. Chuck Python for Informatics's official Podcast. None None 1478713
PY4INF-08-Lists.mp3 Recording by Dr. Chuck Python for Informatics's official Podcast. None None 1636231
PY4INF-09-Dictionaries.mp3 Recording by Dr. Chuck Python for Informatics's official Podcast. None None 2254445
PY4INF-10-Tuples.mp3 Recording by Dr. Chuck Python for Informatics's official Podcast. None None 1597596
PY4INF-11-Regex.mp3 Recording by Dr. Chuck Python for Informatics's official Podcast. None None 2123702
John C. Hollar: History of Computing IEEE Computer Society Computing Conversations 1 None 694073
Bob Metcalfe: Ethernet at Forty IEEE Computer Society Computing Conversations None None 1031392
Gordon Bell: Building Blocks of Computing IEEE Computer Society Computing Conversations 1 None 744620
Ian Horrocks: Standardizing OWL IEEE Computer Society Computing Conversations 1 None 572212
Katie Hafner: The Origins of the Internet IEEE Computer Society Computing Conversations 1 None 652460
Larry Smarr: Building Mosaic IEEE Computer Society Computing Conversations None None 894693
Len Kleinrock: The Theory of Packets IEEE Computer Society Computing Conversations 1 None 674742
Mitchell Baker: The Mozilla Foundation IEEE Computer Society Computing Conversations None None 994246
Pooja Sankar: Building the Piazza Collaboration System IEEE Computer Society Computing Conversations None None 496404
Van Jacobson: Content-Centric Networking IEEE Computer Society Computing Conversations None None 780251
The Apache Software Foundation IEEE Computer Society Computing Conversations None None 542484
A Brief History of Packets IEEE Computer Society Computing Conversations None None 1004643
Discovering JavaScript Object Notation IEEE Computer Society Computing Conversations None None 650971
Inventing PHP IEEE Computer Society Computing Conversations None None 494915
Monash Museum of Computing History IEEE Computer Society Computing Conversations None None 362657
The Rise of JavaScript IEEE Computer Society Computing Conversations None None 526132
Joseph Hardin: NCSA Mosaic IEEE Computer Society Computing Conversations None None 845635

Len Kleinrock on the Internet's First Two Packets IEEE Computer Society Computing Conversations 1 None 594390
Doug Van Houweling on Building the NSFNet IEEE Computer Society Computing Conversations None None 773146
Computing Conversations: Nathaniel Borenstein on MIME IEEE Computer Society Computing Conversations None None 682135
You Don't Mess Around With Jim Jim Croce Classic Hits None None 184398
Andrew S. Tanenbaum on MINIX IEEE Computer Society Computing Conversations None None 603000
Computing Conversations: Elizabeth Fong on SQL Standards IEEE Computer Society Computing Conversations None None 533577
Nii Quaynor on Bringing the Internet to Africa IEEE Computer Society Computing Conversations 1 None 673332
PHP-09-Transactions.mp3 Created by Sakai SI 664 W14's official Podcast. None None 1728888
PHP-01-Intro.mp3 Created by Sakai SI 664 W14's official Podcast. None None 2250624
PHP-02-Install.mp3 Created by Sakai SI 664 W14's official Podcast. 1 None None
PHP-04-Expressions.mp3 Created by Sakai SI 664 W14's official Podcast. None None 2168064
PHP-05-Functions.mp3 Created by Sakai SI 664 W14's official Podcast. None None 1446792
PHP-06-Strings.mp3 Created by Sakai SI 664 W14's official Podcast. None None 417696
PHP-12-Sessions.mp3 Created by Sakai SI 664 W14's official Podcast. None None 3624312
PHP-06-Objects.mp3 Created by Sakai SI 664 W14's official Podcast. None None 2455368
SI664-13-JSON-A.mp3 Created by Sakai SI 664 W14's official Podcast. None None 4407672
PHP-13-JavaScript.mp3 Created by Sakai SI 664 W14's official Podcast. None None 3650088
PHP-09-Database-Design.mp3 Created by Sakai SI 664 W14's official Podcast. None None 3591072
PHP-Tsugi-Install.mp3 Created by Sakai SI 664 W14's official Podcast. None None 3181656
PHP-10-MySQL-PDO.mp3 Created by Sakai SI 664 W14's official Podcast. None None 4536685
PHP-08-MySQL.mp3 Created by Sakai SI 664 W14's official Podcast. None None 3994656
SI664-13-JSON-B.mp3 Created by Sakai SI 664 W14's official Podcast. None None 1484616
IMS-Learning-Tools-Interoperability.mp3 Created by Sakai SI 664 W14's official Podcast. None None 2185848
An Interview with Don Waters Matt Pasiewicz CNI Event Coverage 2 None 1411082
PY4INF-11-Regex.mp3 Recording by Dr. Chuck Python for Informatics's official Podcast. None None 2123702
PY4INF-10-Tuples.mp3 Recording by Dr. Chuck Python for Informatics's official Podcast. None None 1597596
PY4INF-09-Dictionaries.mp3 Recording by Dr. Chuck Python for Informatics's official Podcast. None None 2254445
PY4INF-08-Lists.mp3 Recording by Dr. Chuck Python for Informatics's official Podcast. None None 1636231
PY4INF-07-Files.mp3 Recording by Dr. Chuck Python for Informatics's official Podcast. None None 1478713
PY4INF-06-Strings.mp3 Recording by Dr. Chuck Python for Informatics's official Podcast. None None 1677844
PY4INF-05-Iterations.mp3 Recording by Dr. Chuck Python for Informatics's official Podcast. None None 2804297
PY4INF-04-Functions.mp3 Recording by Dr. Chuck Python for Informatics's official Podcast. None None 1683800
PY4INF-03-Conditional.mp3 Recording by Dr. Chuck Python for Informatics's official Podcast. None None 2296058
PY4INF-02-Expressions.mp3 Recording by Dr. Chuck Python for Informatics's official Podcast. None None 2578416
PY4INF-01-Intro.mp3 Recording by Dr. Chuck Python for Informatics's official Podcast. None None 3428075
Py4Inf-11-Regex.mp3 Recording by Dr. Chuck Python for Informatics's official Podcast. None None 2123702
Py4Inf-10-Tuples.mp3 Recording by Dr. Chuck Python for Informatics's official Podcast. None None 1597596
Py4Inf-09-Dictionaries.mp3 Recording by Dr. Chuck Python for Informatics's official Podcast. None None 2254445
Py4Inf-08-Lists.mp3 Recording by Dr. Chuck Python for Informatics's official Podcast. None None 1636231
Py4Inf-07-Files.mp3 Recording by Dr. Chuck Python for Informatics's official Podcast. None None 1478713
Py4Inf-06-Strings.mp3 Recording by Dr. Chuck Python for Informatics's official Podcast. None None 1677844
Py4Inf-05-Iterations.mp3 Recording by Dr. Chuck Python for Informatics's official Podcast. None None 2804297
Py4Inf-04-Functions.mp3 Recording by Dr. Chuck Python for Informatics's official Podcast. None None 1683800
Py4Inf-03-Conditional.mp3 Recording by Dr. Chuck Python for Informatics's official Podcast. None None 2296058
Py4Inf-02-Expressions.mp3 Recording by Dr. Chuck Python for Informatics's official Podcast. None None 2578416
Py4Inf-01-Intro.mp3 Recording by Dr. Chuck Python for Informatics's official Podcast. None None 3428075
Ian Foster on the Globus Project IEEE Computer Society Computing Conversations 1 None 538305
Khan Academy and Computer Science IEEE Computer Society Computing Conversations 1 None 558837
Guido van Rossumon the Early Years of Python IEEE Computer Society Computing Conversations 1 None 701884
Guido van Rossum on the Modern Era of Python IEEE Computer Society Computing Conversations None None 741616
John Resig on Building jQuery IEEE Computer Society Computing Conversations None None 595983
Roy T. Fielding on Understanding the REST Style IEEE Computer Society Computing Conversations 1 None 683650
Anil Jain: 25 Years of Biometric Recognition IEEE Computer Society Computing Conversations None None 661368
Waste Management Undercover Boss Undercover Boss, Season 1 1 None 2565232
Sleep Like a Baby Tonight U2 Songs of Innocence None None 301641
Evergreen The Black Crowes Warpaint None None 261373
Oh Josephine The Black Crowes Warpaint None None 398907
Movin' On Down the Line The Black Crowes Warpaint None None 342693
Wounded Bird The Black Crowes Warpaint None None 263453
Volcano U2 Songs of Innocence None None 194116
Wee Who See the Deep The Black Crowes Warpaint None None 290520
Cedarwood Road U2 Songs of Innocence None None 265268
Locust Street The Black Crowes Warpaint None None 255240
Raised By Wolves U2 Songs of Innocence None None 245599
The Troubles U2 Songs of Innocence None None 285843
This Is Where You Can Reach Me Now U2 Songs of Innocence None None 305134
God's Got It The Black Crowes Warpaint None None 202653
California (There Is No End to Love) U2 Songs of Innocence None None 239846
Every Breaking Wave U2 Songs of Innocence None None 252162
Interview With the Onion News Network Onion News Network Onion News Network, Season 1 1 None 302002
Song for Someone U2 Songs of Innocence None None 226763
The Miracle (Of Joey Ramone) U2 Songs of Innocence None None 255382
Iris (Hold Me Close) U2 Songs of Innocence None None 319457
Goodbye Daughters of the Revolution The Black Crowes Warpaint None None 304147
Walk Believer Walk The Black Crowes Warpaint None None 280253
Choice Hotels International Undercover Boss Undercover Boss, Season 2 1 None 2614047
Microchip Jason Farnham YouTube Audio Library None None 114336
Anant Agarwal IEEE Computer Society Computing Conversations None None 494000

The output file of the above program is at `'./tracks/trackdb.sqlite'`. To get the full table:  
`SELECT Track.title `__`AS Track_title`__`, Album.title AS Album_title, Artist.name AS Artist_name FROM Track JOIN Album JOIN Artist ON Track.album_id=Album.id AND Album.artist_id=Artist.id`

## 4. Many-to-many relationships in SQL <a name= 'm2m_sql'></a>

> Sometimes the relationships are many-to-many (e.g. authors and publications), therefore a __connection table__ is required to connnect two (or more) foreign keys but no (need for) primary keys.

In [2]:
# Classmembership table with roles as additional input
import json
import sqlite3

conn = sqlite3.connect('./roster/rosterdb.sqlite')
cur = conn.cursor() # one file handle can have multiple cursor
# which executes multiple commands simultaneously

# Do some setup
cur.executescript('''
DROP TABLE IF EXISTS User;
DROP TABLE IF EXISTS Member;
DROP TABLE IF EXISTS Course;

CREATE TABLE User (
    id     INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
    name   TEXT UNIQUE
);

CREATE TABLE Course (
    id     INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
    title  TEXT UNIQUE
);

CREATE TABLE Member (
    user_id     INTEGER,
    course_id   INTEGER,
    role        INTEGER,
    PRIMARY KEY (user_id, course_id)
)
''') # You can define a conbination of fields to be the primary key in a connection table

fname = input('Enter file name: ')
if len(fname) < 1:
    fname = './roster/roster_data_sample.json'

# [
#   [ "Charley", "si110", 1 ],
#   [ "Mea", "si110", 0 ],

# Parse the table as json file
str_data = open(fname).read()
json_data = json.loads(str_data)

for entry in json_data:

    name = entry[0];
    title = entry[1];

    print((name, title))

    cur.execute('''INSERT OR IGNORE INTO User (name)
        VALUES ( ? )''', ( name, ) )
    cur.execute('SELECT id FROM User WHERE name = ? ', (name, ))
    user_id = cur.fetchone()[0]

    cur.execute('''INSERT OR IGNORE INTO Course (title)
        VALUES ( ? )''', ( title, ) )
    cur.execute('SELECT id FROM Course WHERE title = ? ', (title, ))
    course_id = cur.fetchone()[0]
    
    # REPLACE only if the conbination is not unique
    cur.execute('''INSERT OR REPLACE INTO Member
        (user_id, course_id) VALUES ( ?, ? )''',
        ( user_id, course_id ) )

    conn.commit()
    
cur.close()

Enter file name:
('Charley', 'si110')
('Mea', 'si110')
('Hattie', 'si110')
('Lyena', 'si110')
('Keziah', 'si110')
('Ellyce', 'si110')
('Thalia', 'si110')
('Meabh', 'si110')
('Aria', 'si110')
('Reena', 'si110')
('Ioannis', 'si110')
('Reily', 'si110')
('Sidharth', 'si110')
('Keiara', 'si110')
('Yann', 'si110')
('Marykate', 'si110')
('Dylan', 'si110')
('Kiran', 'si110')
('Faizaan', 'si110')
('Aneshia', 'si110')
('Kamron', 'si110')
('Allen', 'si110')
('Marshall', 'si110')
('Rosa', 'si106')
('Nora', 'si106')
('Mairin', 'si106')
('Zendel', 'si106')
('Honie', 'si106')
('Betsy', 'si106')
('Davie', 'si106')
('Larissa', 'si106')
('Shaurya', 'si106')
('Shania', 'si106')
('Sorcha', 'si106')
('Jeanna', 'si106')
('Temba', 'si106')
('Buse', 'si106')
('Mohammed', 'si106')
('Kayah', 'si106')
('Kareena', 'si106')
('Dineo', 'si106')
('Philippa', 'si106')
('Lia', 'si206')
('Sharlyn', 'si206')
('Linton', 'si206')
('Temilade', 'si206')
('Areez', 'si206')
('MacCartney', 'si206')
('Abubakar', 'si206')
('Derryn', 'si206')
('Elan', 'si206')
('Vikki', 'si206')
('Anisa', 'si206')
('Klevis', 'si206')
('Tait', 'si206')
('Rhea', 'si206')
('Pearsen', 'si206')
('Willow', 'si206')
('Skye', 'si206')
('Caralee', 'si206')
('Charlee', 'si206')
('Karyn', 'si206')
('Elana', 'si206')
('Maggie', 'si206')
('Eryk', 'si206')
('Zulaikha', 'si301')
('Elshan', 'si301')
('Anastasia', 'si301')
('Connar', 'si301')
('Anay', 'si301')
('Jayla', 'si301')
('Cai', 'si301')
('Zijie', 'si301')
('Riana', 'si301')
('Codie', 'si301')
('Colette', 'si301')
('Lucee', 'si301')
('Tatiana', 'si301')
('Zhong', 'si301')
('Lowri', 'si301')
('Maggy', 'si301')
('Basher', 'si301')
('Tanika', 'si301')
('Aria', 'si301')
('Belle', 'si301')
('Laranya', 'si301')
('Dayna', 'si301')
('Elleanne', 'si301')
('Maanav', 'si310')
('Tamta', 'si310')
('Frazer', 'si310')
('Sacha', 'si310')
('Aidan', 'si310')
('Abel', 'si310')
('Ahtasham', 'si310')
('Avinash', 'si310')
('Colette', 'si310')
('Cohen', 'si310')
('Rori', 'si310')
('Youer', 'si310')
('Jamey', 'si310')
('Makenzie', 'si310')
('Ida', 'si310')
('Alexzander', 'si310')
('Kavita', 'si310')
('Talia', 'si310')
('Anthony', 'si310')
('Elona', 'si334')
('Inan', 'si334')
('Caoilainn', 'si334')
('Ainsley', 'si334')
('Franciszek', 'si334')
('Corrie', 'si334')
('Nolan', 'si334')
('Makala', 'si334')
('Obieluem', 'si334')
('Camryn', 'si334')
('Honie', 'si334')
('Ole', 'si334')
('Raine', 'si334')
('Tyllor', 'si334')
('Diane', 'si334')
('Cullen', 'si334')
('Taylor', 'si334')
('Schekina', 'si334')
('Kensey', 'si334')
('Zhi', 'si334')
('Kiran', 'si334')
('Tymoteusz', 'si334')
('Windsor', 'si363')
('Kashish', 'si363')
('Diarmid', 'si363')
('Laura', 'si363')
('Jaskaran', 'si363')
('Presley', 'si363')
('Brooklynn', 'si363')
('Heddle', 'si363')
('Travis', 'si363')
('Alx', 'si363')
('Airen', 'si363')
('Erika', 'si363')
('Mackie', 'si363')
('Wen', 'si363')
('Seaan', 'si363')
('Meghan', 'si363')
('Ryaan', 'si363')
('Imogem', 'si364')
('Harlie', 'si364')
('Ronnie', 'si364')
('Lucca', 'si364')
('Shanelle', 'si364')
('Ieuan', 'si364')
('Anneliese', 'si364')
('Simon', 'si364')
('Sorche', 'si364')
('Nawal', 'si364')
('Adelaide', 'si364')
('Rhia', 'si364')
('Katarzyna', 'si364')
('LLeyton', 'si364')
('Enzo', 'si364')
('Declan', 'si364')
('Emelie', 'si364')
('Baillie', 'si364')
('Shola', 'si364')
('Jenna', 'si422')
('Miles', 'si422')
('Sakina', 'si422')
('Melanie', 'si422')
('Bailie', 'si422')
('Cassy', 'si422')
('Nikash', 'si422')
('Hebe', 'si422')
('Sia', 'si422')
('Skyla', 'si422')
('Jamaal', 'si422')
('Keanna', 'si422')
('Vanya', 'si422')
('Temperance', 'si422')
('Hafiza', 'si422')
('Alx', 'si422')
('Brigitte', 'si422')
('Eliana', 'si422')
('Kayden', 'si422')
('Man', 'si422')
('Jaydyn', 'si422')
('Soukina', 'si430')
('Stephenjunior', 'si430')
('Buddy', 'si430')
('Holly', 'si430')
('Kamilia', 'si430')
('Cassie', 'si430')
('Kris', 'si430')
('Maia', 'si430')
('Abel', 'si430')
('Tamika', 'si430')
('Deano', 'si430')
('Rosa', 'si430')
('Georgia', 'si430')
('Louie', 'si430')
('Kassie', 'si430')
('Mutinta', 'si430')
('Manwen', 'si430')

The output file of the above program is at `'./roster/rosterdb.sqlite'`. To get the full table:  
`SELECT Course.title, User.name, Member.role FROM Course JOIN Member JOIN User ON Course.id=Member.course_id and User.id=Member.user_id `__`ORDER BY title, role DESC, name`__

##### Twfriends methods that create a friend relation database <a name= 'twfriends'></a>

In [ ]:
import urllib.request, urllib.parse, urllib.error
import twurl
import json
import sqlite3
import ssl

TWITTER_URL = 'https://api.twitter.com/1.1/friends/list.json'

conn = sqlite3.connect('friends.sqlite')
cur = conn.cursor()

cur.execute('''CREATE TABLE IF NOT EXISTS People
            (id INTEGER PRIMARY KEY, name TEXT UNIQUE, retrieved INTEGER)''')
cur.execute('''CREATE TABLE IF NOT EXISTS Follows
            (from_id INTEGER, to_id INTEGER, UNIQUE(from_id, to_id))''')

# Ignore SSL certificate errors
ctx = ssl.create_default_context()
ctx.check_hostname = False
ctx.verify_mode = ssl.CERT_NONE

while True:
    acct = input('Enter a Twitter account, or quit: ')
    if (acct == 'quit'): break
    if (len(acct) < 1):
        cur.execute('SELECT id, name FROM People WHERE retrieved=0 LIMIT 1')
        try:
            (id, acct) = cur.fetchone()
        except:
            print('No unretrieved Twitter accounts found')
            continue
    else:
        cur.execute('SELECT id FROM People WHERE name = ? LIMIT 1',
                    (acct, ))
        try:
            id = cur.fetchone()[0]
        except:
            cur.execute('''INSERT OR IGNORE INTO People
                        (name, retrieved) VALUES (?, 0)''', (acct, ))
            conn.commit()
            if cur.rowcount != 1:
                print('Error inserting account:', acct)
                continue
            id = cur.lastrowid # used to continue retrieving

    url = twurl.augment(TWITTER_URL, {'screen_name': acct, 'count': '100'})
    print('Retrieving account', acct)
    try:
        connection = urllib.request.urlopen(url, context=ctx)
    except Exception as err:
        print('Failed to Retrieve', err)
        break

    data = connection.read().decode()
    headers = dict(connection.getheaders())

    print('Remaining', headers['x-rate-limit-remaining'])

    try:
        js = json.loads(data)
    except:
        print('Unable to parse json')
        print(data)
        break

    # Debugging
    # print(json.dumps(js, indent=4))

    if 'users' not in js:
        print('Incorrect JSON received')
        print(json.dumps(js, indent=4))
        continue

    cur.execute('UPDATE People SET retrieved=1 WHERE name = ?', (acct, ))

    countnew = 0
    countold = 0
    for u in js['users']:
        friend = u['screen_name']
        print(friend)
        cur.execute('SELECT id FROM People WHERE name = ? LIMIT 1',
                    (friend, ))
        try:
            friend_id = cur.fetchone()[0]
            countold = countold + 1
        except:
            cur.execute('''INSERT OR IGNORE INTO People (name, retrieved)
                        VALUES (?, 0)''', (friend, ))
            conn.commit()
            if cur.rowcount != 1: # if the write is unsuccessful (no hard drive storage)
                print('Error inserting account:', friend)
                continue
            friend_id = cur.lastrowid
            countnew = countnew + 1
        cur.execute('''INSERT OR IGNORE INTO Follows (from_id, to_id)
                    VALUES (?, ?)''', (id, friend_id))
    print('New accounts=', countnew, ' revisited=', countold)
    print('Remaining', headers['x-rate-limit-remaining'])
    conn.commit()

cur.close()

## 5. Databases and visualization <a name= 'visual'></a>
> __Multi-step data analysis__: (online) Data Source -_Gather_-> Raw Database -_Clean/process_-> Clean Data -> Analysis/visualization.

Data mining resources: hadoop, spark, redshift (Amazon), pentaho, etc.

A google Geocode API example.

In [3]:
# Geoload.py
import urllib.request, urllib.parse, urllib.error
import http
import sqlite3
import json
import time
import ssl
import sys

api_key = False
# If you have a Google Places API key, enter it here
# api_key = 'AIzaSy___IDByT70'

if api_key is False:
    api_key = 42
    serviceurl = "http://py4e-data.dr-chuck.net/json?"
else :
    serviceurl = "https://maps.googleapis.com/maps/api/geocode/json?"

# Additional detail for urllib
# http.client.HTTPConnection.debuglevel = 1

conn = sqlite3.connect('./geodata/geodata.sqlite')
cur = conn.cursor()

cur.execute('''
CREATE TABLE IF NOT EXISTS Locations (address TEXT, geodata TEXT)''')

# Ignore SSL certificate errors
ctx = ssl.create_default_context()
ctx.check_hostname = False
ctx.verify_mode = ssl.CERT_NONE

fh = open("./geodata/where.data")
count = 0
for line in fh:
    if count > 200 :
        print('Retrieved 200 locations, restart to retrieve more')
        break

    address = line.strip()
    print('')
    cur.execute("SELECT geodata FROM Locations WHERE address= ?",
        (memoryview(address.encode()), ))

    try:
        data = cur.fetchone()[0]
        print("Found in database ",address)
        continue
    except:
        pass

    parms = dict()
    parms["address"] = address
    if api_key is not False: parms['key'] = api_key
    url = serviceurl + urllib.parse.urlencode(parms)

    print('Retrieving', url)
    uh = urllib.request.urlopen(url, context=ctx)
    data = uh.read().decode()
    print('Retrieved', len(data), 'characters', data[:20].replace('\n', ' '))
    count = count + 1

    try:
        js = json.loads(data)
    except:
        print(data)  # We print in case unicode causes an error
        continue

    if 'status' not in js or (js['status'] != 'OK' and js['status'] != 'ZERO_RESULTS') :
        print('==== Failure To Retrieve ====')
        print(data)
        break

    cur.execute('''INSERT INTO Locations (address, geodata)
            VALUES ( ?, ? )''', (memoryview(address.encode()), memoryview(data.encode()) ) )
    conn.commit()
    if count % 10 == 0 :
        print('Pausing for a bit...')
        time.sleep(5)

print("Run geodump.py to read the data from the database so you can vizualize it on a map.")

Retrieving http://py4e-data.dr-chuck.net/json?address=AGH+University+of+Science+and+Technology&key=42
Retrieved 2315 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Academy+of+Fine+Arts+Warsaw+Poland&key=42
Retrieved 2006 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=American+University+in+Cairo&key=42
Retrieved 1828 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Arizona+State+University&key=42
Retrieved 1802 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Athens+Information+Technology&key=42
Retrieved 2274 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=BITS+Pilani&key=42
Retrieved 1807 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Babcock+University&key=42
Retrieved 1633 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Banaras+Hindu+University&key=42
Retrieved 1989 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Bangalore+University&key=42
Retrieved 2188 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Baylor+University&key=42
Retrieved 2141 characters {    "results" : [
Pausing for a bit...

Retrieving http://py4e-data.dr-chuck.net/json?address=Beijing+normal+university&key=42
Retrieved 2200 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Belarusian+State+University&key=42
Retrieved 4476 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Belgrade+University&key=42
Retrieved 4000 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Beloit+College&key=42
Retrieved 2265 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Belorussian+State+University&key=42
Retrieved 4542 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Ben+Gurion+University&key=42
Retrieved 1927 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Bharthidasan+University&key=42
Retrieved 1893 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Boston+University&key=42
Retrieved 2003 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=California+Polytechnic+State+University+of+San+Luis+Obispo&key=42
Retrieved 1860 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=California+State+University+San+Bernardino&key=42
Retrieved 2182 characters {    "results" : [
Pausing for a bit...

Retrieving http://py4e-data.dr-chuck.net/json?address=City+of+Westminster+College&key=42
Retrieved 2120 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Columbia+University&key=42
Retrieved 1996 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Cranfield+University&key=42
Retrieved 2154 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Czech+Technical+University+in+Prague&key=42
Retrieved 2146 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Dartmouth&key=42
Retrieved 2163 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=De+Anza+College&key=42
Retrieved 4137 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Distant+University+of+Hagen&key=42
Retrieved 2100 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Dnipropetrovsk+National+University&key=42
Retrieved 2442 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Dokuz+Eylul+University&key=42
Retrieved 2127 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Drexel&key=42
Retrieved 2351 characters {    "results" : [
Pausing for a bit...

Retrieving http://py4e-data.dr-chuck.net/json?address=Drexel+University+and+University+of+Texas+at+Austin&key=42
Retrieved 1795 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Duke+University&key=42
Retrieved 1993 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=EM+Lyon&key=42
Retrieved 2129 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Ecole+centrale+de+PARIS&key=42
Retrieved 2326 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Elon+University&key=42
Retrieved 2323 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Erhvervsakademi+Sydvest&key=42
Retrieved 1765 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Escuela+Superior+Politecnica+del+Litoral&key=42
Retrieved 4267 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Fachhochschule+Dusseldorf&key=42
Retrieved 2351 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Fachhochschule+FH+Salzburg&key=42
Retrieved 2110 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Faculdade+de+Tecnologia+do+Estado+de+Sao+Paulo&key=42
Retrieved 2199 characters {    "results" : [
Pausing for a bit...

Retrieving http://py4e-data.dr-chuck.net/json?address=Faculty+of+Technical+Sciences+Novi+Sad+Serbia&key=42
Retrieved 2130 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Farmingdale+State+University&key=42
Retrieved 2133 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Federal+University+of+Minas+Gerais&key=42
Retrieved 2253 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Florida+Atlantic+University&key=42
Retrieved 2137 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Franklin+Pierce+College&key=42
Retrieved 2292 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Gauhati+University&key=42
Retrieved 2026 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=George+Mason+University&key=42
Retrieved 2313 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Georgetown+University+Law+Center&key=42
Retrieved 2187 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Georgia+State+University&key=42
Retrieved 1994 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Grandville&key=42
Retrieved 1752 characters {    "results" : [
Pausing for a bit...

Retrieving http://py4e-data.dr-chuck.net/json?address=Groep+T+University&key=42
Retrieved 2099 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Hanoi+University+of+Science+and+Technology&key=42
Retrieved 1823 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Hebrew+University&key=42
Retrieved 1248 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=IIIT+Hyderabad&key=42
Retrieved 2233 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=IIT+KANPUR&key=42
Retrieved 2029 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=IT+College+of+Estonia&key=42
Retrieved 2089 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=IU&key=42
Retrieved 2314 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=IUAV+Venezia&key=42
Retrieved 2306 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Illinois+Institute+of+Technology&key=42
Retrieved 2275 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Illinois+State+University+Joliet+Junior+College&key=42
Retrieved 2345 characters {    "results" : [
Pausing for a bit...

Retrieving http://py4e-data.dr-chuck.net/json?address=Indian+Institute+of+Technology&key=42
Retrieved 2198 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Indian+Institute+of+Technology+Kharagpur+India&key=42
Retrieved 1817 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Indian+School+of+Mines+Dhanbad&key=42
Retrieved 2580 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Indiana+University&key=42
Retrieved 2314 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Indiana+University+at+Bloomington&key=42
Retrieved 2314 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Institut+Superieur+de+technologies&key=42
Retrieved 4373 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Institute+of+Business+and+Modern+Technologies&key=42
Retrieved 52 characters {    "results" : [],

Retrieving http://py4e-data.dr-chuck.net/json?address=Instituto+Tecnologico+de+Santo+Domingo&key=42
Retrieved 2423 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=International+Institute+of+Information+Technology+Hyderabad&key=42
Retrieved 2233 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Irkutsk+State+University&key=42
Retrieved 4266 characters {    "results" : [
Pausing for a bit...

Retrieving http://py4e-data.dr-chuck.net/json?address=JADAVPUR+UNIVERSITY&key=42
Retrieved 2159 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Jawaharlal+Nehru+Technological+University&key=42
Retrieved 4816 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Jawaharlal+Nehru+University&key=42
Retrieved 1972 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Jordan+University+of+Science+and+Technology&key=42
Retrieved 1474 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=K-State&key=42
Retrieved 1807 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=KUL&key=42
Retrieved 2474 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Kalamazoo+College&key=42
Retrieved 2313 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Kaunas+Technology+University&key=42
Retrieved 2139 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Kaunas+university+of+technology&key=42
Retrieved 2120 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Kazan+Federal+University&key=42
Retrieved 2350 characters {    "results" : [
Pausing for a bit...

Retrieving http://py4e-data.dr-chuck.net/json?address=Kent+State+University&key=42
Retrieved 2120 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Kharkiv+State+Academy+of+Municipal+Economy+Ukraine&key=42
Retrieved 2413 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=King+Mongkuts+University+of+Technology+Thonburi&key=42
Retrieved 2247 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Kokshetau+Institute+of+Economics+and+Management&key=42
Retrieved 1967 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Kyiv+Polytechnic+Institute&key=42
Retrieved 2127 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Kyiv+Polytechnical+Institute&key=42
Retrieved 2160 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Kyiv+Unisersity+of+Oriental+Language&key=42
Retrieved 1699 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Laurentian+University&key=42
Retrieved 2357 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Lisandro+Alvarado&key=42
Retrieved 52 characters {    "results" : [],

Retrieving http://py4e-data.dr-chuck.net/json?address=Lodz+University+of+Technology&key=42
Retrieved 2292 characters {    "results" : [
Pausing for a bit...

Retrieving http://py4e-data.dr-chuck.net/json?address=Lviv+University&key=42
Retrieved 2379 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=MSU&key=42
Retrieved 2162 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Madras+university&key=42
Retrieved 2419 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Magnitogorsk+State+Technical+University&key=42
Retrieved 2209 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Malayer+Azad+University&key=42
Retrieved 1663 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Marietta+College&key=42
Retrieved 4343 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Masdar+Institute&key=42
Retrieved 1733 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Matematicki+fakultet+Beograd&key=42
Retrieved 2107 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Michigan+State+University&key=42
Retrieved 2162 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Middle+East+Technical+University&key=42
Retrieved 2145 characters {    "results" : [
Pausing for a bit...

Retrieving http://py4e-data.dr-chuck.net/json?address=Missouri+University+of+Science+and+Technology&key=42
Retrieved 2478 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Monash&key=42
Retrieved 3503 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Monash+University&key=42
Retrieved 1969 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Monash+University+Churchill+Australia&key=42
Retrieved 3906 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Monterrey+Institute+of+Technology+and+Higher+Education&key=42
Retrieved 2187 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Moscow+Engineering-Physics+Institute&key=42
Retrieved 2373 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Moscow+Institute+of+Physics+%26+Technology&key=42
Retrieved 2189 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Moscow+State+University&key=42
Retrieved 2136 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=NIT+ROURKELA&key=42
Retrieved 2247 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=NYU&key=42
Retrieved 4558 characters {    "results" : [
Pausing for a bit...

Retrieving http://py4e-data.dr-chuck.net/json?address=Nagpur+University&key=42
Retrieved 4279 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Nanyang+Technological+University&key=42
Retrieved 1620 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=National+Institute+of+Technology+Jalandhar&key=42
Retrieved 1818 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=National+Taiwan+University&key=42
Retrieved 2017 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=National+University+of+Engineering&key=42
Retrieved 1882 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=North+Central+College&key=42
Retrieved 2533 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Northeastern+University&key=42
Retrieved 2322 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Northwestern+University&key=42
Retrieved 2130 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Obninsk+Technical+University+of+Nuclear+Power+Engineering+Russia&key=42

Retrieved 2175 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Old+Dominion+University&key=42
Retrieved 1931 characters {    "results" : [
Pausing for a bit...

Retrieving http://py4e-data.dr-chuck.net/json?address=Oregon+Institute+of+Technology&key=42
Retrieved 2138 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=PUCMM&key=42
Retrieved 2213 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Payame+Noor+University&key=42
Retrieved 3621 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Penn+State+University&key=42
Retrieved 1843 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Politecnico+di+Milano&key=42
Retrieved 2345 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Politehnica+University+Bucharest&key=42
Retrieved 2365 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Polytechnic+University+of+Timisoara&key=42
Retrieved 2124 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Pondicherry+University&key=42
Retrieved 2226 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Pontificia+universidad+catolica+de+chile&key=42
Retrieved 2239 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Portland+State+University&key=42
Retrieved 2475 characters {    "results" : [
Pausing for a bit...

Retrieving http://py4e-data.dr-chuck.net/json?address=Purdue+University+Indianapolis&key=42
Retrieved 2352 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=R+V+College+of+Engineering&key=42
Retrieved 2387 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=RPI&key=42
Retrieved 2106 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Ramapo+College+of+New+Jersey&key=42
Retrieved 2286 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Rochester+Institute+of+Technology&key=42
Retrieved 2484 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=SASTRA+University&key=42
Retrieved 1854 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Saint+Petersburg+State+University&key=42
Retrieved 2193 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Saint+Petersburg+State+University+of+Aerospace+Instrumentation&key=42
Retrieved 2196 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Saint-Petersburg+Polytechnic+Univesity&key=42
Retrieved 2228 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=San+Francisco+State+University&key=42
Retrieved 2330 characters {    "results" : [
Pausing for a bit...

Retrieving http://py4e-data.dr-chuck.net/json?address=San+Jose+State+University&key=42
Retrieved 2311 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Shanghai+Jiao+Tong+University&key=42
Retrieved 1668 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Sharif+University+of+Technology&key=42
Retrieved 1471 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Simon+Bolivar+University&key=42
Retrieved 1658 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Simon+Fraser+University&key=42
Retrieved 2144 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Smolensk+State+University&key=42
Retrieved 4322 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Sonoma+State+University&key=42
Retrieved 2152 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=South+Federal+University&key=42
Retrieved 2279 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Spiru+Haret+University&key=42
Retrieved 2347 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Stanford&key=42
Retrieved 1928 characters {    "results" : [
Pausing for a bit...

Retrieving http://py4e-data.dr-chuck.net/json?address=State+University+of+Campinas&key=42
Retrieved 2024 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=State+University+of+New+York+College+at+Oswego&key=42
Retrieved 2114 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Stellenbosch+University&key=42
Retrieved 1903 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Stonehill+College&key=42
Retrieved 2319 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Tallinn+University&key=42
Retrieved 2139 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Tallinn+University+of+Technology&key=42
Retrieved 2116 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Tampere+University+of+Technology&key=42
Retrieved 1441 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Tanta+University&key=42
Retrieved 3713 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Tarrant+County+College&key=42
Retrieved 4419 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Technical+University+of+Cluj-Napoca&key=42
Retrieved 2158 characters {    "results" : [
Pausing for a bit...

Retrieving http://py4e-data.dr-chuck.net/json?address=Technion&key=42
Retrieved 1702 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Tel+Aviv+University&key=42
Retrieved 1474 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=The+Jerusalem+collage+of+engineering&key=42
Retrieved 2407 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=The+University+of+Latvia&key=42
Retrieved 1946 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=The+University+of+Manchester&key=42
Retrieved 1978 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=The+University+of+South+Africa&key=42
Retrieved 2229 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Transilvania+University&key=42
Retrieved 2322 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Tufts+University&key=42
Retrieved 2130 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=UC+Berkeley&key=42
Retrieved 1741 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=UCLA&key=42
Retrieved 2006 characters {    "results" : [
Pausing for a bit...

Retrieving http://py4e-data.dr-chuck.net/json?address=UCSD&key=42
Retrieved 2302 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=UIUC&key=42
Retrieved 1689 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=UMD&key=42
Retrieved 2467 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=UNISA&key=42
Retrieved 2229 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=UNIVERSIDAD+DE+Buenos+Aires&key=42
Retrieved 2132 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=UOC&key=42
Retrieved 2110 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=USC&key=42
Retrieved 2022 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=UW+Madison&key=42
Retrieved 1649 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Universidad+Central+de+Venezuela&key=42
Retrieved 1678 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Universidad+Complutense+de+Madrid&key=42

Retrieved 2083 characters {    "results" : [
Pausing for a bit...

Retrieving http://py4e-data.dr-chuck.net/json?address=Universidad+Cooperativa+de+Colombia&key=42
Retrieved 1825 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Universidad+Nacional+Autonoma+de+Mexico&key=42
Retrieved 1836 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Universidad+Nacional+Costa+Rica&key=42
Retrieved 1664 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Universidad+Nacional+de+Colombia&key=42
Retrieved 1946 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Universidad+Tecnologica+Boliviana&key=42
Retrieved 2185 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Universidad+de+Buenos+Aires&key=42
Retrieved 2132 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Universidad+de+Castilla+La+Mancha&key=42
Retrieved 2157 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Universidad+de+Los+Andes+Colombia&key=42
Retrieved 2083 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Universidad+de+Oriente&key=42
Retrieved 2198 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Universidad+de+San+Carlos+de+Guatemala&key=42
Retrieved 2147 characters {    "results" : [
Pausing for a bit...

Retrieving http://py4e-data.dr-chuck.net/json?address=Universidad+de+Valladolid&key=42
Retrieved 2118 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Universidad+de+la+Sabana&key=42
Retrieved 1829 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Universidad+del+Valle+de+Guatemala&key=42
Retrieved 2021 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Universidade+Federal+da+Paraiba&key=42
Retrieved 1928 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Universidade+Federal+de+Santa+Catarina&key=42
Retrieved 2316 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Universidade+Federal+do+Rio+Grande+do+Sul&key=42
Retrieved 2230 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Universidade+Federal+do+Rio+de+Janeiro&key=42
Retrieved 2377 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Universidade+Tecnica+de+Lisboa&key=42
Retrieved 1920 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Universidade+de+Sao+Paulo&key=42
Retrieved 3528 characters {    "results" : [

Retrieving http://py4e-data.dr-chuck.net/json?address=Universidade+do+Minho&key=42
Retrieved 1782 characters {    "results" : [
Pausing for a bit...

Retrieving http://py4e-data.dr-chuck.net/json?address=Universitas+Gadjah+Mada&key=42
Retrieved 2312 characters {    "results" : [
Retrieved 200 locations, restart to retrieve more
Run geodump.py to read the data from the database so you can vizualize it on a map.

Raw sqlite data (with json tables) was parsed with `geodump` and put into 'where.js'.

In [4]:
# Geodump.py
import sqlite3
import json
import codecs

conn = sqlite3.connect('./geodata/geodata.sqlite')
cur = conn.cursor()

cur.execute('SELECT * FROM Locations')
fhand = codecs.open('./geodata/where.js', 'w', "utf-8")
fhand.write("myData = [\n")
count = 0
for row in cur :
    data = str(row[1].decode())
    try: js = json.loads(str(data))
    except: continue

    if not('status' in js and js['status'] == 'OK') : continue

    lat = js["results"][0]["geometry"]["location"]["lat"]
    lng = js["results"][0]["geometry"]["location"]["lng"]
    # Primitive data cleaning
    if lat == 0 or lng == 0 : continue
    where = js['results'][0]['formatted_address']
    where = where.replace("'", "")
    try :
        print(where, lat, lng)

        count = count + 1
        if count > 1 : fhand.write(",\n")
        output = "["+str(lat)+","+str(lng)+", '"+where+"']"
        fhand.write(output)
    except:
        continue

fhand.write("\n];\n")
cur.close()
fhand.close()
print(count, "records written to where.js")
print("Open where.html to view the data in a browser")

aleja Adama Mickiewicza 30, 30-059 Kraków, Poland 50.06688579999999 19.9136192
Krakowskie Przedmieście 5, 00-068 Warszawa, Poland 52.2394019 21.0150792
AUC Avenue، Road، First New Cairo, Cairo Governorate 11835, Egypt 30.018923 31.499674
Tempe, AZ 85281, USA 33.4242399 -111.9280527
2500 Daniells Bridge Rd #300, Athens, GA 30606, USA 33.9094132 -83.4603953
Vidya Vihar, Pilani, Rajasthan 333031, India 28.3588163 75.58802039999999
Ilishan-Remo, Nigeria 6.8939569 3.7187158
Ajagara, Varanasi, Uttar Pradesh 221005, India 25.2677203 82.99125819999999
Main Rd, Gnana Bharathi, Bengaluru, Karnataka 560056, India 12.9504351 77.5021998
1301 S University Parks Dr, Waco, TX 76706, USA 31.5497007 -97.1143046
19 Xinjiekou Outer St, Bei Tai Ping Zhuang, Haidian Qu, Beijing Shi, China, 100875 39.9619537 116.3662615
praspiekt Niezaliežnasci 4, Minsk, Belarus 53.8938988 27.5460609
Studentski trg 1, Beograd, Serbia 44.8184518 20.4575913
700 College St, Beloit, WI 53511, USA 42.5030333 -89.0309048
praspiekt Niezaliežnasci 4, Minsk, Belarus 53.8938988 27.5460609
שד בן-גוריון 1, באר שבע, Israel 31.262218 34.801461
Palkalaiperur, Tiruchirappalli, Tamil Nadu 620024, India 10.6779085 78.74454879999999
Boston, MA 02215, USA 42.3504997 -71.1053991
San Luis Obispo, CA 93407, USA 35.3050053 -120.6624942
5500 University Pkwy, San Bernardino, CA 92407, USA 34.1817955 -117.3237219
25 Paddington Green, London W2 1NB, UK 51.5210038 -0.1746353
New York, NY 10027, USA 40.8075355 -73.9625727
College Rd, Cranfield, Bedford MK43 0AL, UK 52.0746136 -0.6282833
Zikova 1903/4, 166 36 Praha 6, Czechia 50.1030364 14.3912841
Hanover, NH 03755, USA 43.7044406 -72.2886935
21250 Stevens Creek Blvd, Cupertino, CA 95014, USA 37.3206678 -122.0454878
Universitätsstraße 47, 58097 Hagen, Germany 51.377409 7.4921548
Haharina Ave, 72, Dnipropetrovsk, Dnipropetrovska oblast, Ukraine, 49000 48.4331922 35.0427966
Kültür, Cumhuriyet Blv No:144, 35220 Konak/İzmir, Turkey 38.4306911 27.1369201
3141 Chestnut St, Philadelphia, PA 19104, USA 39.9566127 -75.18994409999999
Austin, TX 78712, USA 30.2849185 -97.7340567
Durham, NC 27708, USA 36.0014258 -78.9382286
23 Avenue Guy de Collongue, 69130 Écully, France 45.7864448 4.7641329
CentraleSupélec, 3 Rue Joliot Curie, 91190 Gif-sur-Yvette, France 48.7087594 2.1640062
50 Campus Drive, Elon, NC 27244, USA 36.1026877 -79.5023313
Spangsbjerg Kirkevej 103, 6700 Esbjerg, Denmark 55.48843069999999 8.4467103
Vía Perimetral 5, Guayaquil, Ecuador -2.1481458 -79.9644885
Münsterstraße 156, 40476 Düsseldorf, Germany 51.2468622 6.791686899999999
Urstein Süd 1, 5412 Puch bei Hallein, Austria 47.7233835 13.0871253
Av. Tiradentes, 615 - Bom Retiro, São Paulo - SP, 01124-060, Brazil -23.5295544 -46.6325856
Trg Dositeja Obradovića 6, Novi Sad 106314, Serbia 45.2461012 19.8516968
2350 NY-110, Farmingdale, NY 11735, USA 40.7529512 -73.4267093
Av. Pres. Antônio Carlos, 6627 - Pampulha, Belo Horizonte - MG, 31270-901, Brazil -19.870682 -43.9677359
777 Glades Rd, Boca Raton, FL 33431, USA 26.3749876 -80.10106329999999
40 University Dr, Rindge, NH 03461, USA 42.7790898 -72.05560229999999
Jalukbari, Guwahati, Assam 781014, India 26.1543199 91.66316789999999
4400 University Dr, Fairfax, VA 22030, USA 38.8298118 -77.3073606
600 New Jersey Ave NW, Washington, DC 20001, USA 38.8977953 -77.0129087
Atlanta, GA 30302, USA 33.753068 -84.38528190000001
Grandville, MI, USA 42.9097484 -85.7630885
Andreas Vesaliusstraat 13, 3000 Leuven, Belgium 50.8748769 4.7077753
1 Đại Cồ Việt, Bách Khoa, Hai Bà Trưng, Hà Nội, Vietnam 21.0048067 105.8453406
Jerusalem 31.7945578 35.2414009
Professor CR Rao Rd, Gachibowli, Hyderabad, Telangana 500032, India 17.4448019 78.3497604
Kalyanpur, Kanpur, Uttar Pradesh 208016, India 26.5123388 80.2329
Raja 4, 12616 Tallinn, Estonia 59.3954769 24.6643815
107 S Indiana Ave, Bloomington, IN 47405, USA 39.1754487 -86.512627
Santa Croce, 191, 30135 Venezia VE, Italy 45.4377642 12.3226561
10 W 35th St, Chicago, IL 60616, USA 41.8348731 -87.6270059
100 N University St, Normal, IL 61761, USA 40.5120479 -88.9931683
IIT Campus, Hauz Khas, New Delhi, Delhi 110016, India 28.5449756 77.19262839999999
Kharagpur, West Bengal 721302, India 22.3149274 87.31053109999999
Police Line Rd, IIT (ISM, Hirapur, Sardar Patel Nagar, Dhanbad, Jharkhand 826004, India 23.8143819 86.44120219999999
107 S Indiana Ave, Bloomington, IN 47405, USA 39.1754487 -86.512627
107 S Indiana Ave, Bloomington, IN 47405, USA 39.1754487 -86.512627
3230 Rue Sicotte, Saint-Hyacinthe, QC J2S 2M2, Canada 45.618372 -72.9675991
Av. de Los Próceres 49, Santo Domingo 10602, Dominican Republic 18.487876 -69.96229199999999
Professor CR Rao Rd, Gachibowli, Hyderabad, Telangana 500032, India 17.4448019 78.3497604
Karl Marx St, 1, Irkutsk, Irkutskaya oblast, Russia, 664003 52.2766124 104.2777287
Jadavpur university gate, 3, Jadavpur, Kolkata, West Bengal 700032, India 22.4988822 88.3714123
Ashok Nagar, Kukatpally Housing Board Colony, Kukatpally, Hyderabad, Telangana 500085, India 17.4932682 78.3913929
New Mehrauli Road, JNU Ring Rd, New Delhi, Delhi 110067, India 28.540214 77.1661949
Ar Ramtha 3030، Ar-Ramtha, Jordan 32.4950392 35.9912257
Manhattan, KS 66506, USA 39.1974437 -96.5847249
1 Hospital Dr, Columbia, MO 65212, USA 38.938273 -92.3273842
1200 Academy St, Kalamazoo, MI 49006, USA 42.290035 -85.598145
K. Baršausko g. 59, Kaunas 51423, Lithuania 54.89951019999999 23.9615303
K. Donelaičio g. 73, Kaunas 44249, Lithuania 54.898991 23.912825
Kremlyovskaya St, 18, Kazan, Respublika Tatarstan, Russia, 420008 55.790447 49.1214349
800 E Summit St, Kent, OH 44240, USA 41.1455594 -81.33928829999999
Marshala Bazhanova St, 17, Kharkiv, Kharkivska oblast, Ukraine, 61000 49.9953598 36.242221
126 Pracha Uthit Rd, Khwaeng Bang Mot, Khet Thung Khru, Krung Thep Maha Nakhon 10140, Thailand 13.6510248 100.4953802
Kokshetau 020000, Kazakhstan 53.2871307 69.40444939999999
Peremohy Ave, 37, Kyiv, Ukraine, 03056 50.4491694 30.4561475
Peremohy Ave, 37, Kyiv, Ukraine, 03056 50.4491694 30.4561475
Kyiv, Ukraine, 02000 50.4501 30.5234
935 Ramsey Lake Rd, Sudbury, ON P3E 2C6, Canada 46.4667708 -80.9742332
Stefana Żeromskiego 116, 90-924 Łódź, Poland 51.7537146 19.4517176
Universytetska St, 1, Lviv, Lvivska oblast, Ukraine, 79000 49.8406108 24.0225099
220 Trowbridge Rd, East Lansing, MI 48824, USA 42.701848 -84.4821719
Navalar Nagar, Chepauk, Triplicane, Chennai, Tamil Nadu 600005, India 13.0660293 80.28317190000001
Prospekt Lenina, 38, Magnitogorsk, Chelyabinskaya oblast, Russia, 455000 53.4222397 58.9824868
Hamadan Province, Malayer, University Blvd, Iran 34.304073 48.8452846
215 5th St, Marietta, OH 45750, USA 39.41665649999999 -81.44993509999999
Near Home WTC AUH, Airport Road - Masdar City - Abu Dhabi - United Arab Emirates 24.4330231 54.619113
Studentski trg 16, Beograd 105104, Serbia 44.8199188 20.4587075
220 Trowbridge Rd, East Lansing, MI 48824, USA 42.701848 -84.4821719
Üniversiteler, Dumlupınar Blv. No:1, 06800 Çankaya/Ankara, Turkey 39.8910203 32.7780027
106, Parker Hall, 300 W 13th St, Rolla, MO 65409, USA 37.9536715 -91.7756278
Wellington Rd, Clayton VIC 3800, Australia -37.9105599 145.1362485
Wellington Rd, Clayton VIC 3800, Australia -37.9105599 145.1362485
Northways Rd, Churchill VIC 3842, Australia -38.311211 146.429409
Av. Eugenio Garza Sada 2501 Sur, Tecnológico, 64849 Monterrey, N.L., Mexico 25.6515649 -100.28954
Kashira Hwy, 31, Moskva, Russia, 115409 55.6499374 37.6641161
Institutskiy Pereulok, 9, Dolgoprudny, Moskovskaya oblast, Russia, 141701 55.9297243 37.5199434
ul. Leninskiye Gory, 1, Moskva, Russia, 119991 55.70393490000001 37.5286696
National Institute of Technology, Sector 1, Rourkela, Odisha 769008, India 22.2533781 84.9012363
New York, NY 10003, USA 40.72951339999999 -73.9964609
Amravati Rd, Ram Nagar, Nagpur, Maharashtra 440033, India 21.1468555 79.050062
50 Nanyang Ave, Singapore 639798 1.3483099 103.6831347
Grand Trunk Road, Bye pass, Jalandhar, Punjab 144011, India 31.3961507 75.5353566
No. 1, Section 4, Roosevelt Rd, Da’an District, Taipei City, Taiwan 10617 25.0173405 121.5397518
Avenida Tupac Amaru 210 Apartado 1301, Rímac 15333, Peru -12.0237376 -77.04837739999999
30 N Brainard St, Naperville, IL 60540, USA 41.772663 -88.1440142
360 Huntington Ave, Boston, MA 02115, USA 42.3398067 -71.0891717
633 Clark St, Evanston, IL 60208, USA 42.0564594 -87.67526699999999
Студенческий городок, 1, Obninsk, Kaluzhskaya oblast, Russia, 249034 55.1372019 36.6064735
5115 Hampton Blvd, Norfolk, VA 23529, USA 36.8841106 -76.304239
3201 Campus Dr, Klamath Falls, OR 97601, USA 42.2573474 -121.7849109
Autopista Duarte Km 1 1/2, Santiago De Los Caballeros 51000, Dominican Republic 19.4436005 -70.6843785
Tehran Province, Tehran, اتوبان ارتش کوی نفت, Nakhl St, Iran 35.8012314 51.5028533
State College, PA 16801, USA 40.7982133 -77.8599084
Piazza Leonardo da Vinci, 32, 20133 Milano MI, Italy 45.4784315 9.228342399999999
Splaiul Independenței 313, București 060042, Romania 44.4386064 26.0494925
Piața Victoriei 2, Timișoara 300006, Romania 45.7536393 21.2251615
Pondicherry University, Chinna Kalapet, Kalapet, Puducherry 605014, India 12.0182619 79.8568461
Av Libertador Bernardo OHiggins 340, Santiago, Región Metropolitana, Chile -33.4411794 -70.64075679999999
1825 SW Broadway, Portland, OR 97201, USA 45.5111014 -122.6833472
420 University Blvd, Indianapolis, IN 46202, USA 39.77435 -86.1763446
Mysore Rd, RV Vidyaniketan, Post, Bengaluru, Karnataka 560059, India 12.9237228 77.4987012
110 8th St, Troy, NY 12180, USA 42.7297628 -73.67888839999999
505 Ramapo Valley Rd, Mahwah, NJ 07430, USA 41.0819323 -74.1758157
1 Lomb Memorial Dr, Rochester, NY 14623, USA 43.0844955 -77.6749311
Trichy-Tanjore Road, Thirumalaisamudram, Thanjavur, Tamil Nadu 613401, India 10.7285131 79.0184111
University Embankment, 7/9, Sankt-Peterburg, Russia, 199034 59.941894 30.2989199
Bolshaya Morskaya Ulitsa, 67, Sankt-Peterburg, Russia, 190000 59.929491 30.2966081
Politekhnicheskaya Ulitsa, 29, Sankt-Peterburg, Russia, 195251 60.00744979999999 30.3729617
1600 Holloway Ave, San Francisco, CA 94132, USA 37.7241492 -122.4799405
1 Washington Sq, San Jose, CA 95192, USA 37.3351874 -121.8810715
China, Shanghai Shi, Minhang Qu, 东川路 邮政编码: 200240 31.0252201 121.4337784
Tehran, خیابان آزادی، تهران بزرگ،، Iran 35.7036361 51.35156199999999
Sartenejas, Caracas, Miranda, Venezuela 10.408363 -66.8755735
8888 University Dr, Burnaby, BC V5A 1S6, Canada 49.2780937 -122.9198833
Ulitsa Przhevalskogo, 4, Smolensk, Smolenskaya oblast, Russia, 214000 54.7845032 32.0452469
1801 E Cotati Ave, Rohnert Park, CA 94928, USA 38.3395854 -122.6743811
29020 8th Ave S, Federal Way, WA 98003, USA 47.3410976 -122.3242639
Strada Ion Ghica 13, București 030045, Romania 44.4332166 26.1009718
450 Serra Mall, Stanford, CA 94305, USA 37.4274745 -122.169719
Cidade Universitária Zeferino Vaz - Barão Geraldo, Campinas - SP, 13083-970, Brazil -22.8184393 -47.0647206
7060 NY-104, Oswego, NY 13126, USA 43.45139280000001 -76.5425285
Stellenbosch Central, Stellenbosch, South Africa -33.9328078 18.864447
320 Washington St, North Easton, MA 02357, USA 42.0590153 -71.0806276
Narva maantee 25, 10120 Tallinn, Estonia 59.4387321 24.7713836
Ehitajate tee 5, 12616 Tallinn, Estonia 59.3959451 24.6710596
Korkeakoulunkatu 7 Kampusareena, 33720 Tampere, Finland 61.4498286 23.8589986
El-Gaish, Tanta Qism 2, Tanta, Gharbia Governorate, Egypt 30.7924391 30.9991409
1500 Houston St, Fort Worth, TX 76102, USA 32.7474661 -97.3278753
Strada Memorandumului 28, Cluj-Napoca 400114, Romania 46.769299 23.585613
Linkkikatu 15, 21100 Naantali, Finland 60.4706859 22.0694608
Tel Aviv-Yafo, Israel 32.1133141 34.8043877
Velachery Main Rd, Narayanapuram, Pallikaranai, Chennai, Tamil Nadu 600100, India 12.9452892 80.207843
Raiņa bulvāris 19, Centra rajons, Rīga, LV-1586, Latvia 56.95080979999999 24.1163132
Oxford Rd, Manchester M13 9PL, UK 53.4668498 -2.2338837
Preller St, Muckleneuk, Pretoria, 0002, South Africa -25.7676588 28.1992637
300 N Broadway, Lexington, KY 40508, USA 38.0516801 -84.49334189999999
419 Boston Ave, Medford, MA 02155, USA 42.4074843 -71.1190232
Berkeley, CA, USA 37.8718992 -122.2585399
Los Angeles, CA 90095, USA 34.068921 -118.4451811
9500 Gilman Dr, La Jolla, CA 92093, USA 32.8800604 -117.2340135
Champaign, IL, USA 40.1019523 -88.2271615
1049 University Dr, Duluth, MN 55812, USA 46.8173234 -92.0846134
Preller St, Muckleneuk, Pretoria, 0002, South Africa -25.7676588 28.1992637
Viamonte 430, C1053 CABA, Argentina -34.5998875 -58.37306949999999
Rambla del Poblenou, 156, 08018 Barcelona, Spain 41.4063164 2.1947066
Los Angeles, CA 90007, USA 34.0223519 -118.285117
Madison, WI, USA 43.076592 -89.4124875
Caracas, Capital District, Venezuela 10.4883502 -66.8891696
Av. Séneca, 2, 28040 Madrid, Spain 40.4454368 -3.7299424
Bucaramanga, Santander, Colombia 7.1297913 -73.1136365
University City, Coyoacán, 04510 Mexico City, CDMX, Mexico 19.332465 -99.1847825
Avenida 1, Calle 9 Heredia 86, Heredia, 3000, Costa Rica 9.9986898 -84.11118979999999
Cra 45, Bogotá, Colombia 4.6381938 -74.08404639999999
Calle Colombia 154, La Paz, Bolivia -16.500656 -68.134299
Viamonte 430, C1053 CABA, Argentina -34.5998875 -58.37306949999999
Av. Camilo José Cela, 50, 13071 Ciudad Real, Cdad. Real, Spain 38.99404390000001 -3.9204979
Cra. 1 #18a 12, Bogotá, Cundinamarca, Colombia 4.6014864 -74.0663881
Via Alterna, Barcelona 6001, Anzoátegui, Venezuela 10.1732454 -64.6525884
11 Av, Guatemala 01012, Guatemala 14.587349 -90.55341399999999
C/Plaza de Santa Cruz, 8, 47002 Valladolid, Spain 41.6569271 -4.7140547
Universidad De La Sabana,, Chía, Cundinamarca, Colombia 4.861509799999999 -74.0313247
18 Avenida 11-95 Guatemala, Guatemala 01015, Guatemala 14.603762 -90.48924799999999
Campus I - Lot. Cidade Universitaria, João Pessoa - PB, 58051-900, Brazil -7.1377579 -34.8458995
R. Eng. Agronômico Andrei Cristian Ferreira, s/n - Trindade, Florianópolis - SC, 88040-900, Brazil -27.6000837 -48.5194214
Av. Paulo Gama, 110 - Farroupilha, Porto Alegre - RS, 90040-060, Brazil -30.0336054 -51.2198408
Av. Pedro Calmon, 550 - Cidade Universitária da Universidade Federal do Rio de Janeiro, Rio de Janeiro - RJ, 21941-901, Brazil -22.8617077 -43.2234035
Av. Rovisco Pais 1, 1049-001 Lisboa, Portugal 38.7368192 -9.138705
Butanta, São Paulo - State of São Paulo, Brazil -23.5613991 -46.7307891
R. da Universidade, 4710-057 Braga, Portugal 41.5607319 -8.3962368
Bulaksumur, Caturtunggal, Kec. Depok, Kabupaten Sleman, Daerah Istimewa Yogyakarta 55281, Indonesia -7.7713847 110.3774998
199 records written to where.js
Open where.html to view the data in a browser

The result is shown as a [webpage](./geodata/geodata_BAK/where.html) and the code is as shown below in JS. <a name= 'jsgeo'></a>

In [ ]:
<html>
  <head>
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
    <meta charset="utf-8">
    <title>A Map of Information</title>
    <link href="https://google-developers.appspot.com/maps/documentation/javascript/examples/default.css" rel="stylesheet">

    <!-- If you are in China, you may need to use theis site for the Google Maps code
    <script src="https://maps.google.cn/maps/api/js" type="text/javascript"></script> -->
    
    <script src="https://maps.googleapis.com/maps/api/js"></script>
    <script src="where.js"></script>
    <script>

      function initialize() {
        alert("To see the title of a marker, hover over the marker but don't click.");
        var myLatlng = new google.maps.LatLng(37.39361,-122.099263)
        var mapOptions = {
          zoom: 3,
          center: myLatlng,
          mapTypeId: google.maps.MapTypeId.ROADMAP
        }
        var map = new google.maps.Map(document.getElementById('map_canvas'), mapOptions);

        i = 0;
        var markers = [];
        for ( pos in myData ) {
            i = i + 1;
            var row = myData[pos];
		    window.console && console.log(row);
            // if ( i < 3 ) { alert(row); }
            var newLatlng = new google.maps.LatLng(row[0], row[1]);
            var marker = new google.maps.Marker({
                position: newLatlng,
                map: map,
                title: row[2]
            });
            markers.push(marker);
<!-- New options for MarkerClusterer function to display markers -->
	    var options = {
			imagePath: 'http://rawgit.com/googlemaps/js-marker-clusterer/gh-pages/images/m'
			}	
        }
<!-- New var -->
	var markerCluster = new MarkerClusterer(map, markers, options);
      }
    </script>
  </head>
  <body onload="initialize()">
<div id="map_canvas" style="height: 500px"></div>
<p><b>About this Map</b></p>
<p>
This is a cool map from 
<a href="https://www.py4e.com">www.py4e.com</a>.
</p>
</body>
</html>